const endpoints = {
  statistics: "/statistics",
  getProfile: "/auth/profile",
  updateProfile: "/auth/profile",
  home: "/home",
  getOrders: "/orders",
  getOrder: "/orders/",
  editOrder: "/orders/",
  logIn: "/auth/login",
  sendVerifyCode: "/auth/send/verification-code",
  resetPassword: "/auth/reset-password",
  logout: "/auth/logout",
  getZones: "/zones",
  deleteZone: "/zones/",
  createZone: "/zones",
  updateZone: "/zones/",
  getCoupons: "/coupons",
  deleteCoupon: "/coupons/",
  createCoupon: "/coupons",
  updateCoupon: "/coupons/",
  getSliders: "/sliders",
  deleteSlider: "/sliders/",
  createSlider: "/sliders",
  updateSlider: "/sliders/",
  getUsers: "/users",
  deleteUser: "/users/",
  updateUser: "/users/",
  createUser: "/users",
  getNotifs: "/auth/notifications",
  getContacts: "/contact-us",
  deleteContact: "/contact-us/",
  replyContactApi: "/contact-us/reply/",
  getCategories: "/sections",
  deleteCategory: "/sections/",
  createCategory: "/sections",
  updateCategory: "/sections/",
  getProduct: "/products/",
  getProducts: "/products",
  deleteProduct: "/products/",
  updateProduct: "/products/",
  createProduct: "/products",
  getRatings: (id: string | number) => `/products/${id}/ratings`,
  deleteRating: (id1: string | number, id2: string | number) =>
    `/products/ratings/${id2}`,
  downlaodFile: (id: string | number) => `/products/${id}/download`,
};

export default endpoints;
